build(tools): skip lib type check
This might some bugs need to be investigated.
`error TS2420: Class 'Readable' incorrectly implements interface 'ReadableStream'.`